version: '3.3'
services:
  soap_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soap_service
    env_file:
      - .env
    ports:
      - '${APP_PORT:-8080}:${APP_PORT:-8080}'
    volumes:
      - .:/var/www/html
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: soap_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '9906:3306'
    expose:
      - '3306'
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d